### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dimaxjon** [xYantix/snowdump#1]
python3 snowdump.py -t https://example.service-now.com -u admin -p pass
Attempting to dump: ast_lease
Traceback (most recent call last):
  File "snowdump.py", line 30, in <module>
    data = json.loads(response.text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by xYantix** [comment]
Can you provide some more info on this one? Happy to work on improving this script since it has been a while since I looked at it but I don't have a current Service Now instance to test with. Feel free to follow/DM me on Twitter if you can share a URL - @xyantix
